/**
 * @fileoverview Cloud CNC Controller Config
 */

//Import
const fs = require('fs');

//Export
module.exports = {
  controller: {
    //Controller ID (Part of key's filename)
    _id: '5e152a7467ea760af01b9fd4',

    //Controller key directory (Generated by GUI)
    key: './crypto/key.txt',

    //Logging directory (Only used in production)
    logs: './logs/',

    //Serialport auto-reconnect delay (MS)
    serialDelay: 3000,

    //Websocket auto-reconnect delay (MS)
    websocketDelay: 3000
  },
  core: {
    //Websocket URL of core server
    url: 'wss://127.0.0.1'
  },
  machines: [
    {
      _id: '5e152b0e67ea760af01b9fd5',
      enabled: true,
      path: 'COM3',
      baudRate: 250000
    }
  ]

/*  //Cryptography
  crypto: {
    //Key generated by the GUI
    key: fs.readFileSync('./crypto/key.txt', 'utf8')
  },
  //Core server information
  core: {
    //Websocket URL of core
    url: 'wss://127.0.0.1'
  },
  //Logging
  logging: {
    //Output directory (Only used in production)
    directory: './logs/'
  },
  //Connected machines
  machines: [
    {
      _id: '5e152b0e67ea760af01b9fd5',
      enabled: true,
      path: 'COM3',
      baudRate: 250000
    }
  ],
  //Meta information
  meta: {
    //Controller ID
    _id: '5e152a7467ea760af01b9fd4',

    //Auto-reconnect delay (ms)
    delay: 3000
  }*/
};