/**
 * @fileoverview Default development Cloud CNC controller config
 * This config file uses sain defaults
 */

//Export
module.exports = {
  controller: {
    //Controller ID (Part of key's filename)
    _id: '',

    //Controller key directory (Generated by GUI)
    key: './config/key.txt',

    //Logging directory (Only used in production)
    logs: './logs/',

    //Serialport auto-reconnect delay (MS)
    serialDelay: 3000,

    //Maximum number of attempts to reconnect to machine before notifying core (Set to -1 to never stop)
    maximumSerialAttempts: 10,

    //Websocket auto-reconnect delay (MS)
    websocketDelay: 3000,

    //Maximum number of attempts to reconnect to core server before failing (Set to -1 to never stop)
    maximumWebsocketAttempts: 10,

    //After reaching the maximum attempts, run the specified failsafe command for every machine
    failsafe: true
  },
  core: {
    //TLS certificate (Used for trusting self signed certificates) (PEM encoded)
    cert: './config/cert.cer',

    //Self signed (Trust self signed certificates installed on the core server)
    selfSigned: true,

    //Websocket URL of core server (With URI scheme)
    url: 'wss://127.0.0.1'
  },
  //List of machines this controller should control
  machines: [
    {
      _id: '',
      failsafe: 'M112\n',
      path: '',
      baudRate: 0
    }
  ]
};