name: Tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [13, 14]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - uses: stefanoeb/eslint-action@master
        name: ESLint
      - name: Cleanup
        run: sudo rm -rf node_modules
      - name: Install Modules
        run: sudo npm ci
      - name: Create Directories
        run: sudo mkdir /data/db -p
      - name: Generate Key
        run: cd config && openssl rand -out key.txt -base64 512
      - uses: paambaati/codeclimate-action@v2.6.0
        name: Run Tests
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: sudo npm run coverage