name: tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Modules
        run: sudo npm ci
      - name: Create Directories
        run: mkdir crypto files && sudo mkdir /data/db -p
      - name: Generate Key
        run: cd crypto && openssl rand -out key.txt -base64 512
      - name: Test
        run: sudo npm test
