name: Tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 13]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: stefanoeb/eslint-action@1.0.2
        name: ESLint
      - name: Install Modules
        run: sudo npm ci
      - name: Cleanup
        run: sudo rm -rf /home/runner/work/controller/controller/node_modules
      - name: Create Directories
        run: mkdir crypto files && sudo mkdir /data/db -p
      - name: Generate Key
        run: cd crypto && openssl rand -out key.txt -base64 512
      - uses: paambaati/codeclimate-action@v2.4.0
        name: Test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: sudo npm run coverage