name: tests
on: push
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Install Modules
        run: npm i -D
      - name: Debug 1
        run: node --version
      - name: Debug 2
        run: nodejs --version
      - name: Create Directories
        run: mkdir crypto files && sudo mkdir /data/db -p
      - name: Generate Key
        run: cd crypto && openssl rand -out key.txt -base64 512
      - name: Test
        run: sudo npm test
